services:
  db:
    image: postgres:16.4-alpine
    container_name: playground_db
    environment:
      POSTGRES_DB: playground_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d playground_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: playground_app
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/playground_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
    driver: local